apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: kargo-demo-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
  annotations:
    kargo.akuity.io/authorized-projects: kargo-demo
stringData:
  type: git
  project: default
  url: https://github.com/ashreesee/kargo-demo-new.git
  username: ashreesee
  password: wkvWVFP786xBxv@