apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: test
  namespace: kargo-helm
spec:
  subscriptions:
    repos:
      version:
      - repoURL: https://charts.bitnami.com/bitnami
        semverConstraint: ^12.0.3
  promotionMechanisms:
    gitRepoUpdates:
    - repoURL: https://github.com/pratik3686/kargo-demo-new
      writeBranch: stage/test
      kustomize:
        images:
        - image: https://charts.bitnami.com/bitnami
          path: helmapp/stages/test
    argoCDAppUpdates:
    - appName: kustomize-thanos-app-test
      appNamespace: argocds