apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: test
  namespace: kargo-demo
spec:
  subscriptions:
    repos:
      images:
      - repoURL: ghcr.io/ashreesee/backend
        semverConstraint: ^0.0.1
  promotionMechanisms:
    gitRepoUpdates:
    - repoURL: https://github.com/ashreesee/kargo-demo-new
      writeBranch: stage/test
      kustomize:
        images:
        - image: ghcr.io/ashreesee/backend
          path: stages/test
    argoCDAppUpdates:
    - appName: kargo-demo-test
      appNamespace: argocd