apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend  # Fixed indentation
          image: ashreesee/backend:v1
          ports:
            - containerPort: 3000  # Fixed indentation
          env:
            - name: DB_HOST
              value: "mysql-service"
            - name: DB_USER
              value: "root"
            - name: DB_PASSWORD
              value: "qwerty"
            - name: DB_NAME
              value: "my_new_db"
              