apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
      annotations:
        argocd-image-updater.argoproj.io/image-list: "frontend=ashreesee/frontend" 
        argocd-image-updater.argoproj.io/allowed-images: "ashreesee/frontend:.*"
    spec:
      containers:
        - name: frontend  # Fixed indentation
          image: ashreesee/frontend:v1
          ports:
            - containerPort: 5000  # Fixed indentation
          env:
            - name: REACT_APP_API_URL
              value: "http://backend-service:3000/"
